name: 'LaunchDarkly Code References'
description: 'Find references to feature flags in your code.'
author: 'LaunchDarkly'
branding:
  icon: toggle-right
  color: gray-dark
inputs:
  projKey:
    description: 'Key of the LaunchDarkly project associated with this repository. Found under Account Settings -> Projects in the LaunchDarkly dashboard. Cannot be combined with `projects` block in configuration file.'
    required: false
  accessToken:
    description: 'Token with write access to LaunchDarkly project.'
    required: true
  repoName:
    description: 'Sets the repository name for this project. This is useful if you have a single monorepo containing multiple YAML configurations each mapping to its own projKey. Each YAML configuration must have a unique LD_PROJ_KEY and LD_REPO_NAME combination so it displays correctly in the LaunchDarkly dashboard. Defaults to the current Github repository.'
  baseUri:
    description: 'Set the base URL of the LaunchDarkly server for this configuration.'
    default: 'https://app.launchdarkly.com'
  contextLines:
    description:
      The number of context lines above and below a code reference for the job to send to LaunchDarkly. By default, the flag finder will not send any context lines to LaunchDarkly. If < 0, no source code will be sent to LaunchDarkly. If 0, only the lines containing flag references will be sent. If > 0, will send that number of context lines above and below the flag reference. A maximum of 5 context lines may be provided.
    default: 2
  allowTags:
    description: Enables storing references for tags. The tag will be listed as a branch.
    default: false
  debug:
    description: Enables verbose debug logging.
    default: false
  ignoreServiceErrors:
    description: If enabled, the scanner will terminate with exit code 0 when the LaunchDarkly API is unreachable or returns an unexpected response.
    default: false
  lookback:
    description: 'Sets the number of Git commits to search in history for
whether a feature flag was removed from code. May be set to 0 to disabled this feature. Setting this option to a high value will increase search time.'
    default: 10
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    LD_PROJ_KEY: ${{ inputs.projKey }}
    LD_ACCESS_TOKEN: ${{ inputs.accessToken }}
    LD_REPO_NAME: ${{ inputs.repoName }}
    LD_BASE_URI: ${{ inputs.baseUri }}
    LD_CONTEXT_LINES: ${{ inputs.contextLines }}
    LD_ALLOW_TAGS: ${{ inputs.allowTags }}
    LD_DEBUG: ${{ inputs.debug }}
    LD_IGNORE_SERVICE_ERRORS: ${{ inputs.ignoreServiceErrors }}
    LD_LOOKBACK: ${{ inputs.lookback }}
