name: LaunchDarkly Code References
description: Find references to feature flags in your code.
author: LaunchDarkly
branding:
  icon: toggle-right
  color: gray-dark
inputs: 
  accessToken: 
    description: "A token with write access to the LaunchDarkly project."
    required: true
  allowTags: 
    default: "false"
    description: "Enable storing references for tags. Lists the tag as a branch."
    required: false
  baseUri: 
    default: "https://app.launchdarkly.com"
    description: "The base URL of the LaunchDarkly server for this configuration."
    required: false
  contextLines: 
    default: "2"
    description: "The number of context lines above and below a code reference for the job to send to LaunchDarkly. By default, the flag finder will not send any context lines to LaunchDarkly. If < 0, it will send no source code to LaunchDarkly. If 0, it will send only the lines containing flag references. If > 0, it will send that number of context lines above and below the flag reference. You may provide a maximum of 5 context lines."
    required: false
  debug: 
    default: "false"
    description: "Enable verbose debug logging."
    required: false
  ignoreServiceErrors: 
    default: "false"
    description: "If enabled, the scanner will terminate with exit code 0 when the LaunchDarkly API is unreachable or returns an unexpected response."
    required: false
  lookback: 
    default: "10"
    description: "Set the number of commits to search in history for whether you removed a feature flag from code. You may set to 0 to disable this feature. Setting this option to a high value will increase search time."
    required: false
  projKey: 
    description: "Key of the LaunchDarkly project associated with this repository. Found under Account Settings -> Projects in the LaunchDarkly dashboard. Cannot be combined with `projects` block in configuration file."
    required: false
  repoName: 
    description: "The repository name. Defaults to the current GitHub repository."
    required: false
  prune:
    default: "false"
    description: "There is a known issue where the GitHub Action will not prune deleted branch data in private repos. Only enable this if you are running the action in a public repo."
    required: false
  subdirectory:
    description: "The subdirectory to run the action in."
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    LD_PROJ_KEY: ${{ inputs.projKey }}
    LD_ACCESS_TOKEN: ${{ inputs.accessToken }}
    LD_REPO_NAME: ${{ inputs.repoName }}
    LD_BASE_URI: ${{ inputs.baseUri }}
    LD_CONTEXT_LINES: ${{ inputs.contextLines }}
    LD_ALLOW_TAGS: ${{ inputs.allowTags }}
    LD_DEBUG: ${{ inputs.debug }}
    LD_IGNORE_SERVICE_ERRORS: ${{ inputs.ignoreServiceErrors }}
    LD_LOOKBACK: ${{ inputs.lookback }}
    LD_PRUNE: ${{ inputs.prune }}
    LD_SUBDIRECTORY: ${{ inputs.subdirectory }}
